import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

// Register fonts (optional - using system fonts)
Font.register({
  family: "Inter",
  fonts: [
    { src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2", fontWeight: 400 },
    { src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiA.woff2", fontWeight: 700 },
  ],
});

const styles = StyleSheet.create({
  page: {
    fontFamily: "Inter",
    fontSize: 11,
    paddingTop: 60,
    paddingLeft: 60,
    paddingRight: 60,
    paddingBottom: 60,
    lineHeight: 1.6,
    backgroundColor: "#ffffff",
  },
  title: {
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 20,
    color: "#111827",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 40,
    textAlign: "center",
  },
  section: {
    marginBottom: 20,
  },
  heading1: {
    fontSize: 20,
    fontWeight: 700,
    marginBottom: 12,
    marginTop: 24,
    color: "#111827",
  },
  heading2: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 10,
    marginTop: 18,
    color: "#374151",
  },
  heading3: {
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 8,
    marginTop: 14,
    color: "#4b5563",
  },
  paragraph: {
    fontSize: 11,
    marginBottom: 10,
    color: "#374151",
    textAlign: "justify",
  },
  listItem: {
    fontSize: 11,
    marginBottom: 4,
    marginLeft: 20,
    color: "#374151",
  },
  bullet: {
    width: 10,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 60,
    right: 60,
    textAlign: "center",
    color: "#9ca3af",
    fontSize: 9,
  },
  pageNumber: {
    position: "absolute",
    bottom: 30,
    right: 60,
    color: "#9ca3af",
    fontSize: 9,
  },
});

interface WhitepaperPDFProps {
  title: string;
  content: string;
}

// Simple markdown parser for PDF rendering
function parseMarkdown(content: string): React.ReactNode[] {
  const lines = content.split("\n");
  const elements: React.ReactNode[] = [];
  let listItems: string[] = [];
  let key = 0;

  const flushList = () => {
    if (listItems.length > 0) {
      elements.push(
        <View key={key++} style={{ marginBottom: 10 }}>
          {listItems.map((item, i) => (
            <View key={i} style={{ flexDirection: "row", marginBottom: 4 }}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.listItem}>{item}</Text>
            </View>
          ))}
        </View>
      );
      listItems = [];
    }
  };

  for (const line of lines) {
    const trimmed = line.trim();

    // Empty line
    if (!trimmed) {
      flushList();
      continue;
    }

    // Headings
    if (trimmed.startsWith("### ")) {
      flushList();
      elements.push(
        <Text key={key++} style={styles.heading3}>
          {trimmed.slice(4)}
        </Text>
      );
    } else if (trimmed.startsWith("## ")) {
      flushList();
      elements.push(
        <Text key={key++} style={styles.heading2}>
          {trimmed.slice(3)}
        </Text>
      );
    } else if (trimmed.startsWith("# ")) {
      flushList();
      elements.push(
        <Text key={key++} style={styles.heading1}>
          {trimmed.slice(2)}
        </Text>
      );
    }
    // List items
    else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      listItems.push(trimmed.slice(2));
    } else if (/^\d+\.\s/.test(trimmed)) {
      listItems.push(trimmed.replace(/^\d+\.\s/, ""));
    }
    // Regular paragraph
    else {
      flushList();
      // Remove markdown bold/italic for simplicity
      const cleaned = trimmed
        .replace(/\*\*([^*]+)\*\*/g, "$1")
        .replace(/\*([^*]+)\*/g, "$1")
        .replace(/__([^_]+)__/g, "$1")
        .replace(/_([^_]+)_/g, "$1");

      elements.push(
        <Text key={key++} style={styles.paragraph}>
          {cleaned}
        </Text>
      );
    }
  }

  flushList();
  return elements;
}

export function WhitepaperPDF({ title, content }: WhitepaperPDFProps) {
  const parsedContent = parseMarkdown(content);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>
          Generated by Sovereign Mint • {new Date().toLocaleDateString()}
        </Text>

        <View style={styles.section}>{parsedContent}</View>

        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
